orchestrator:
  llm_info:
    chat_template: "You are a helpful assistant."
    creativity: 0.7
  llm_train:
    enabled: false
    params:
      - "--epochs"
      - "10"
  db_connection:
    host: "localhost"
    port: 5432
    user: "admin"
    password: "securepassword"
  logging:
    level: "INFO"
    format: "standard"
  health_checks:
    interval_seconds: 3600
    enabled: true
  error_recovery:
    auto_restart: true
    retry_intervals: [1, 5, 15]